# syntax=docker/dockerfile:1

# Build react client
FROM node:18-alpine AS builder

# Working directory be app
WORKDIR /usr/src/app

COPY package*.json ./

###  Installing dependencies

RUN npm install --omit=dev

# copy local files to app folder
COPY . .

RUN npm run build

# Copy secondary caddy stage
FROM caddy:2.6-alpine

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=builder /usr/src/app/dist/ /srv

EXPOSE 80
EXPOSE 443 


