version: '3.7'

services:
  api-server:
    container_name: api-server
    image: api-server
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/config/dev.env
    ports: 
      - 4000:4000
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - app-network
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
  
  mongo:
    container_name: mongo
    image: mongo:6.0-focal
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network
  
  react-app:
    container_name: react-app
    image: react-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - api-server
    depends_on:
      - api-server
    networks:
      - app-network
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge  