version: '3.7'

services:
  api-server:
    container_name: api-server-production
    image: api-server-production
    restart: unless-stopped
    environment:
      - MONGO_URI=${MONGO_URI}
      - port=${port}
      - SECRET_KEY=${SECRET_KEY}
      - SALT_WORK_FACTOR=${SALT_WORK_FACTOR}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - INITIAL_USER_EMAIL=${INITIAL_USER_EMAIL}
      - INITIAL_USER_PASSW=${INITIAL_USER_PASSW}
    ports: 
      - 4000:4000
  
  react-app:
    container_name: react-app-production
    image: react-app-production:${ENV}
    ports:
      - 80:80
      - 443:443
    links:
      - api-server
    depends_on:
      - api-server
    volumes:
      - caddy-data:/data
      - caddy-config:/config
  

volumes:
  caddy-data:
    driver: local
  caddy-config:
    driver: local