build-dev:
	docker build -t api-server .

build-local:
	docker build -t api-server-production -f Dockerfile.production .

build-production:
	docker build -t api-server-production -f Dockerfile.production .